### ISSUE TITLE
Please attribute the original author of README.targets & Solution creator per LICENSE stipulation

### ISSUE THREAD

**Issue by Maverik** [bls220/Void_Crew_Mods#1]
I've spent days crafting the readme targets file and released it happily with only stipulation of being credited when my work is used.

Overall, I can see from your entire project has used my entire solution structure and metadata and plugged your values in. While I'm happy for you to use it (and thus its open source), not crediting any of my work is very ironic, considering you're even using my license model so I expect you to know its stipulations.

I'm hoping its a simple oversight and would be rectified swiftly.

Many thanks in advance!

**Comment by bls220** [comment]
Apologies! I had originally had a repo-level README that properly attributed you. My assumption is that I accidentally blew it away while I was adding the Clean target and didn't notice while dealing with the frustration of Thunderstore being down last night. I will make a super small README right now and add it back.

Again apologies and thanks for reaching out!

**Comment by Maverik** [comment]
No problem at all! I went with the assumption that it was unintentional and thank you for swift response!

**Comment by bls220** [comment]
Attribution added in https://github.com/bls220/Void_Crew_Mods/commit/7b436e55a4840ad37a3657f676025c2c15687107.
Let me know if there is anything you would like me to add.

Happy Moding!

**Comment by Maverik** [comment]
That is perfect. You've actually also made me think I can add blurb in project files so when they get used, they mostly attribute the original work on their own unless someone goes out of their way to take that out.

Much appreciated. Also love your SkipIntro mod and looking forward to testing FoV. I already run @ 100 to be able to see battery charge during engineering. Thank you for your work there.

**Comment by bls220** [comment]
Glad to here it! I have "Dual Ultra-Wide" (5140X1440) so the playing in full screen at full resolution felt like playing through a magnifying glass without increased FoV.

As for the batteries, I think there is a bug with batteries being picked up in a half-thrown position. If you can't see the bar, simply tap Right Click and pick them up again. 😄

**Comment by Maverik** [comment]
Oh interesting, no I haven't run into battery bug yet or haven't noticed it. No it's the fact they're so close to your face you can't see them charging up. But @ 100 you can tell when they're about 80-90% and charging up in your hand so you know when they're full.

Also I find my 4K painful in most games, I'm not sure how you manage dual ultra wide though that'd be a drooling setup for coding!

**Comment by bls220** [comment]
Thanks for heads up!

Also great find with ConfigurationManager! That is probably also the same reason [ScriptEngine](https://github.com/BepInEx/BepInEx.Debug#scriptengine) also doesn't work.

I had started looking into why ConfigurationManager was not working, but stopped since I didn't have any crucial configuration I wanted to add to my mods. I had originally wanted the max number of players to be customizable, however, after play testing 8 seems to be a good max due to increased lag. If I decide I need configuration, I will probably make your lib mod a dependency, to reduce running duplicate code.

**Comment by Maverik** [comment]
Indeed ScriptEngine also had the same issue as did GraphicsSettings mod. I tried raising it with both Thunderstore & Bepinex.. neither wants to do something so I just did it myself in my library to get things moving.
