### ISSUE TITLE
Update 3.0 causing object reference  error in line 15 of MatchmakingRoomSetupPatch.cs

### ISSUE THREAD

**Issue by JC-Cervidae** [bls220/Void_Crew_Mods#3]
Hey there! Recent fan of void crew and by extension, your mod! The newest update seems to have renamed one of the files referenced in your mod, which seems to be keeping it from functioning properly (even checking the max player count setting in game). 

I tried taking a look at the code myself, but I'm not at all experienced in this language. I'll happily provide any logs you may need if you could just direct me towards them, but I'm very excited for this mod to be functional again. Please do let me know if there is anything I can do to assist in rectifying the errors!

**Comment by bls220** [comment]
Thanks for letting me know! I haven't played since the update dropped.

I will look at this ASAP. If not tomorrow then, I'll probably have time this weekend.

**Comment by bls220** [comment]
New version is uploaded now!
I wasn't able to run though a full test, but I was able to start a game.

Again, big thanks for letting me know this was broken. I checked the discord and apparently it had been talked about but no one let me know.

If you find any other issues, I'm happy to take a look.

**Comment by JC-Cervidae** [comment]
Thanks so much for your incredible swiftness in resolving this! We'll be certain to test out a couple 5-6 people runs very soon.

**Comment by JC-Cervidae** [comment]
Testing out the mod just now and receiving a different error when attempting to run, this time I remembered to capture the logs. We're still testing to see if it definitely doesn't work, but we're having some troubles getting everyone into a lobby after setting the max player count. Only mods that are installed at this time are the BepinEx package, Mavs Core, and Voider Crew.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MatchmakingHandler+<>c__DisplayClass17_0.<GetSteamAuthTicket>g__OnAuthCallback|0 (Steamworks.GetTicketForWebApiResponse_t callback) (at <02f42d15ba7841d28c6685b6340528e6>:0)
Steamworks.Callback`1[T].OnRunCallback (System.IntPtr pvParam) (at <2575c35bf1884977b1c5cf21c1cfbc5b>:0)
UnityEngine.Debug:LogException(Exception)
Steamworks.CallbackDispatcher:ExceptionHandler(Exception)
Steamworks.Callback`1:OnRunCallback(IntPtr)
Steamworks.CallbackDispatcher:RunFrame(Boolean)
Steamworks.SteamAPI:RunCallbacks()
SteamManager:Update()

**Comment by bls220** [comment]
Interesting, I didn't see this when doing a solo game set to 8 players.
Does this occur when someone joins the game?

**Comment by JC-Cervidae** [comment]
I edited my previous comment, but you got to it so fast! 

What we've noticed is that the error in the BepinEx 5.4.21.0 window will appear when multiple users with the mod are in the same lobby. 4 players are able to join without issue, but the 5th player receives an " Error: . " message and is disconnected from the lobby and temporarily from the game server as well (_this is rectified by swapping servers and back_).

Two other notable observations: 

- The recurrence of the below error regarding a disconnect state
![image](https://github.com/bls220/Void_Crew_Mods/assets/102497688/b2a4194b-0e6f-4d01-928b-3a2b2d90123a)

- When selecting the max number of players on a given matchmaking terminal, it isn't synced between the 3 possible terminals. Each terminal will read 4 max players until changed individually, but this did not make the game work.

**Comment by bls220** [comment]
Yeah, the terminals have never been sync'd, not even in vanilla.

Unfortunately, I have been struggling to get 5 people together that are willing to help me test the mod.

**Comment by DrunkenUnicyclist** [comment]
I've got a group of 4+ willing to help with this. Please reach out and we can work on scheduling.

**Comment by JC-Cervidae** [comment]
Likewise, we'd be happy to assist wherever we can, and I'd bet you've got tons of volunteers over on the Discord as well.
