### ISSUE TITLE
Voider Crew not working for some players

### ISSUE THREAD

**Issue by Magus7** [bls220/Void_Crew_Mods#4]
I'm unsure how exactly to format this, given the lack of information I have to work with, but I've encountered an issue in which the "Voider Crew" mod for Void Crew is not working for certain players. Some of the player base have no apparent issues with it and routinely use it, but my friends and I have all downloaded it via Thunderstore Mod Manager and we all have the latest version (0.0.2 at the time of writing this report). I'd greatly appreciate any advice you could give in terms of troubleshooting this issue, or at least gathering information. Thanks in advance for any help you're able to provide!

**Comment by JC-Cervidae** [comment]
Commenting to add my two cents to this, I'm getting the same issue. Happy to provide my log file if it helps.

**Comment by Magus7** [comment]
Update as of today: Following some testing, the mod consistently allows everyone in my play group to see the enhanced player slider (up to 8 maximum), but as soon as the 5th player attempts to join, they immediately receive the "connection lost" error message and are unable to start a new game until they relaunch Void Crew.

This is reproducible across the following variables:
- multiple different sessions, 
- started by multiple different players 
- using the mod installed via Thunderstore and the mod installed directly via manual download.

**Comment by bls220** [comment]
@JC-Cervidae / @Magus7 , I just uploaded a new version of the mod. Let me know if you are still having issues.

This to note:
* The Matchmaking terminals will not sync, (they never have)
* If a non-modded player joins your lobby, you will have to adjust the max players down then up again.

**Comment by Magus7** [comment]
Look like that last update fixed it; just completed a 3-objective mission with a crew of 5! Thanks very much for your work!
