### ISSUE TITLE
Update Endless

### ISSUE THREAD

**Issue by Kirbyfan1223** [bls220/Void_Crew_Mods#5]
The mod wont work on the new update
![image](https://github.com/bls220/Void_Crew_Mods/assets/7103684/3c990cbd-4d90-4807-b21c-a71ac6d9100e)

**Comment by DragonFire47** [comment]
KirbyFan, could you provide more details about the issue? What mod is causing this, what are you doing when it happens? The image details an exception from the player character network data, and may in fact be a vanilla issue.

**Comment by Kirbyfan1223** [comment]
The mod I am having issues with is Voider Crew. I am able to add the slider past 4 but anyone who joins when there is 4 gets a server communication error and cannot join. These are the mods I have installed.
![image](https://github.com/bls220/Void_Crew_Mods/assets/7103684/9ca1c737-bfec-4ae2-b345-b05d6e101d18)

**Comment by bls220** [comment]
Thank @DragonFire47!

@Kirbyfan1223, if you don't mind could you try again without InGameRoomMenu?
If that doesn't work, could you try Voider_Crew by itself?

**Comment by Kirbyfan1223** [comment]
Sorry for the delay message. I got my friends together and it did work. There was an update to the InGameRoomMenu to fix the compatibility with this mod.
